version: '3'

services:

  redis:
    container_name: 'redis-container'
    # image: redis/redis-stack:latest
    image: redis:latest
    ports:
      - "6379:6379"
      # - "8001:8001"
    networks:
      - redis-network


  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-container
    env_file:
      - ./environ_file
    ports:
      - "1433:1433"
    networks:
      - redis-network


  producer:
    container_name: producer-container
    build:
      context: .
      dockerfile: Dockerfile.producer
    command: python -u app.py
    env_file:
      - ./environ_file
    depends_on:
      - redis
    networks:
      - redis-network


  consumer:
    container_name: consumer-container
    build:
      context: .
      dockerfile: Dockerfile.consumer
    command: python -u consumer.py
    env_file:
      - ./environ_file
    depends_on:
      - redis
      - mssql
    networks:
      - redis-network

networks:
  redis-network: