version: '3'

services:
  flask-app:
    build:
      context: ./
      dockerfile: DockerFile
    image: flaskassign/app
    container_name: flask-app
    ports:
      - "5000:5000"
    env_file:
      - ./env_variables
    command: "python -u main.py"
    depends_on:
      - db
    restart: always


  db:
    build: 
      context: ./db
      dockerfile: DockerFile
    container_name: mssql-db
    env_file:
      - ./env_variables
    ports:
        - 1434:1434