version: '3'

services:

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"


  consumer:
    container_name: consumer-container
    build:
      context: .
      dockerfile: Dockerfile.consumer
    command: python -u consumer.py
    env_file:
      - ./env_variables
    depends_on:
      - redis